env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - prettier
overrides:
  - files:
      - src/**/*.ts
      - src/*.ts
ignorePatterns:
  - src-js/
rules:
  '@typescript-eslint/no-explicit-any':
    - warn
    - ignoreRestArgs: true
